import { ArrowLeft, ArrowRight, CheckCircle2, Eye, Layers3, MonitorSmartphone, Palette, Sparkles, Target } from "lucide-react";
import { createFileRoute } from "@tanstack/react-router";
import { BrandMark } from "@/components/marketing/brand";
import { SiteFooter } from "@/components/marketing/site-footer";
import { WhatsAppFloat } from "@/components/marketing/whatsapp-float";

export const Route = createFileRoute("/proyectos/persianas-blackout")({
  head:()=>({meta:[
    {title:"Persianas & Black Out — Caso de Estudio | Cómplice Lab"},
    {name:"description",content:"Caso de estudio de Persianas & Black Out: marca, identidad, dirección creativa y comunicación comercial creadas desde cero."},
    {property:"og:title",content:"Persianas & Black Out — Caso de Estudio | Cómplice Lab"},
    {property:"og:description",content:"Creamos desde cero una marca de persianas y soluciones de control de luz con identidad, concepto y sistema visual propio."},
    {property:"og:url",content:"https://complicelab.com/proyectos/persianas-blackout"},
    {property:"og:image",content:"https://complicelab.com/og-image.jpg"},
    {name:"twitter:card",content:"summary_large_image"},
  ],links:[{rel:"canonical",href:"https://complicelab.com/proyectos/persianas-blackout"}]}),
  component:PersianasCase,
});
const whatsapp="https://api.whatsapp.com/send?phone=+573161772880&text=Hola.%20Quiero%20hablar%20sobre%20un%20proyecto%20de%20marca%20como%20Persianas%20%26%20Black%20Out.";
const capabilities=[
 ["Marca desde cero",Palette,"Definición visual y conceptual para construir una marca reconocible desde el primer contacto."],
 ["Dirección creativa",Sparkles,"Un lenguaje visual elegante, limpio y adaptable a comunicación comercial y digital."],
 ["Concepto visual",Eye,"La marca se construyó alrededor de luz, privacidad, confort y transformación de espacios."],
 ["Sistema gráfico",Layers3,"Tipografía, composición, recursos visuales y aplicaciones pensadas para mantener consistencia."],
 ["Comunicación comercial",Target,"Mensajes orientados a mostrar beneficio, estética y funcionalidad sin depender de tecnicismos."],
 ["Aplicación digital",MonitorSmartphone,"La identidad se preparó para funcionar en piezas, redes y futuros puntos de contacto digitales."],
] as const;
function BrandBoard(){return <div className="pb-brand-board"><div className="pb-logo-panel"><div><div className="pb-mark">P&amp;B</div><h3>PERSIANAS &amp; BLACK OUT</h3><p>Diseño · Privacidad · Control de luz</p></div></div><div className="pb-material-panel"><div className="pb-material"/><div className="pb-material"/><div className="pb-material"/><div className="pb-material"/></div></div>}
function SpaceShowcase(){return <div className="pb-space-showcase"><div className="pb-space-card"><div className="pb-scene-window"/><div className="pb-scene-copy"><small>CONCEPTO VISUAL</small><h3>La luz también diseña el espacio.</h3></div></div><div className="pb-space-side"><article><Eye/><h3>Más que cubrir una ventana</h3><p>La propuesta comunica control, ambiente y privacidad como parte del diseño interior.</p></article><article><Sparkles/><h3>Una marca limpia y premium</h3><p>Se evitó el lenguaje visual genérico del sector para construir una presencia más sobria y aspiracional.</p></article><article><Layers3/><h3>Preparada para crecer</h3><p>El sistema visual puede extenderse a catálogos, redes, publicidad y futuros canales digitales.</p></article></div></div>}
function PersianasCase(){return <div className="case-page pb-case"><header className="formation-nav case-nav"><div className="nav-wrap"><BrandMark/><a className="formation-back" href="/#proyectos"><ArrowLeft size={16}/> Volver a proyectos</a><a className="button button-sm" href={whatsapp} target="_blank" rel="noreferrer noopener">Hablemos</a></div></header><main>
<section className="case-hero"><div className="hero-grid" aria-hidden="true"/><div className="container"><p className="eyebrow">CASO DE ESTUDIO · BRANDING</p><div className="case-hero-grid"><div><h1>Persianas<br/><span>&amp; Black Out</span></h1><p className="case-hero-lead">Creamos desde cero una marca enfocada en diseño, privacidad y control de luz para espacios residenciales y comerciales.</p><div className="case-service-tags">{["Branding","Identidad","Dirección creativa","Contenido","Comercial"].map(x=><span key={x}>{x}</span>)}</div></div><div className="case-metrics"><div><strong>0→1</strong><span>marca construida desde cero</span></div><div><strong>360°</strong><span>identidad pensada para múltiples aplicaciones</span></div><div><strong>P&amp;B</strong><span>sistema visual propietario</span></div><div><strong>1</strong><span>concepto central: controlar la luz con diseño</span></div></div></div><div className="case-hero-preview"><div className="project-visual project-visual-pb" style={{minHeight:520}}><div className="pb-room"><div className="pb-window"><div className="pb-blind-top"/><div className="pb-blind"/><div className="pb-pull"><i/></div></div><div className="pb-light"/><div className="pb-brand-lockup"><span>P&amp;B</span><strong>PERSIANAS &amp; BLACK OUT</strong><small>CONTROL DE LUZ · PRIVACIDAD · DISEÑO</small></div><div className="pb-swatches"><i/><i/><i/><i/></div></div></div></div></div></section>
<section className="section"><div className="container case-story-grid"><div><p className="eyebrow">EL PUNTO DE PARTIDA</p><h2>Una empresa nueva necesitaba verse como una <span className="pb-accent">marca real desde el primer día.</span></h2></div><div className="case-story-copy"><p>Persianas &amp; Black Out fue creada desde cero como proyecto empresarial de Cristian. No existía una identidad previa: había que construir concepto, lenguaje, estética y forma de presentar el servicio.</p><p>La oportunidad estaba en salir del código visual típico del sector y construir una presencia más limpia, elegante y preparada para crecer.</p><strong>No diseñamos solamente un logo. Diseñamos una base de marca capaz de sostener un negocio.</strong></div></div></section>
<section className="section section-deep"><div className="container"><div className="section-heading"><p className="eyebrow">IDENTIDAD</p><h2>Una marca pensada para <span className="pb-accent">vestir espacios.</span></h2><p>La dirección visual toma elementos del producto —formas limpias, planos, luz y sombra— y los convierte en un lenguaje reconocible.</p></div><BrandBoard/></div></section>
<section className="section"><div className="container"><div className="section-heading"><p className="eyebrow">QUÉ CONSTRUIMOS</p><h2>Una identidad que puede vivir en <span className="pb-accent">todo el recorrido comercial.</span></h2></div><div className="case-capabilities">{capabilities.map(([title,Icon,copy])=><article key={title}><Icon/><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
<section className="section section-deep"><div className="container"><div className="section-heading"><p className="eyebrow">DIRECCIÓN VISUAL</p><h2>Control de luz convertido en <span className="pb-accent">lenguaje de marca.</span></h2><p>Como todavía no contamos con fotografías propias del proyecto, usamos una presentación conceptual coherente con la marca sin inventar instalaciones ni resultados.</p></div><SpaceShowcase/></div></section>
<section className="case-result"><div className="container"><p className="eyebrow">EL RESULTADO</p><h2>Una marca nueva con una base visual lista para <span>salir al mercado y seguir creciendo.</span></h2><div className="case-result-pills"><span><CheckCircle2/> Marca creada desde cero</span><span><Palette/> Identidad propia</span><span><Sparkles/> Dirección creativa</span><span><MonitorSmartphone/> Preparada para digital</span></div></div></section>
<section className="main-cta formation-cta"><div className="container"><p className="eyebrow">¿QUIERES CREAR UNA MARCA DESDE CERO?</p><h2>Tu idea también puede tener una <span className="case-accent-light">identidad que se sienta propia.</span></h2><p>Construimos concepto, marca, comunicación y presencia digital alrededor de tu negocio.</p><div className="hero-actions"><a className="button button-light" href={whatsapp} target="_blank" rel="noreferrer noopener">Hablemos <ArrowRight size={18}/></a><a className="button button-outline-light" href="/#proyectos">Ver más proyectos</a></div></div></section>
</main><SiteFooter/><WhatsAppFloat/></div>}
